name: Build (MATLAB)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: R2024b
          products: Simulink

      - name: Run script
        uses: matlab-actions/run-command@v3
        with:
          command: build_matlab